[package]
name = "tokenization"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.fm)"]

[dependencies]
share = { local = ".." }
receipt_fixture = { local = "fixtures/receipt", modes = ["test"] }
